/**
 * Two-way map between MCP/HTTP command names (`get-current-url`, derived
 * from `kelpie_get_current_url`) and the CLI phrases people type (`url`).
 * Used by the LLM help system to find metadata and to answer
 * `kelpie --llm-help <either form>`.
 */

export const endpointToCliCommandAliases: Record<string, string> = {
  "get-current-url": "url",
  "get-dom": "dom",
  "query-selector": "query",
  "get-element-text": "text",
  "get-accessibility-tree": "a11y",
  "screenshot-annotated": "annotate",
  "click-annotation": "click-index",
  "fill-annotation": "fill-index",
  "get-visible-elements": "visible",
  "get-page-text": "page-text",
  "get-form-state": "form-state",
  "get-console-messages": "console",
  "get-js-errors": "errors",
  "get-network-log": "network",
  "get-resource-timeline": "timeline",
  "get-websockets": "websockets",
  "get-websocket-messages": "ws-messages",
  "wait-for-element": "wait",
  "wait-for-navigation": "wait-nav",
  "get-device-info": "info",
  "get-viewport": "viewport",
  "get-shadow-roots": "shadow-roots",
  "query-shadow-dom": "shadow-query",
  "set-home": "home set",
  "get-home": "home get",
  "get-debug-overlay": "debug-overlay get",
  "set-debug-overlay": "debug-overlay set",
  "get-dialog": "dialog check",
  "handle-dialog": "dialog accept",
  "set-dialog-auto-handler": "dialog auto",
  "get-tabs": "tabs",
  "new-tab": "tab new",
  "get-partitions": "partitions",
  "delete-partition": "partition delete",
  "switch-tab": "tab switch",
  "close-tab": "tab close",
  "get-iframes": "iframes",
  "switch-to-iframe": "iframe enter",
  "switch-to-main": "iframe exit",
  "get-iframe-context": "iframe context",
  "get-cookies": "cookies",
  "set-cookie": "cookies set",
  "delete-cookies": "cookies delete",
  "get-storage": "storage",
  "set-storage": "storage set",
  "clear-storage": "storage clear",
  "get-clipboard": "clipboard",
  "set-clipboard": "clipboard set",
  "set-geolocation": "geo set",
  "clear-geolocation": "geo clear",
  "show-keyboard": "keyboard show",
  "hide-keyboard": "keyboard hide",
  "get-keyboard-state": "keyboard state",
  "resize-viewport": "keyboard resize",
  "reset-viewport": "keyboard resize-reset",
  "is-element-obscured": "keyboard obscured",
  "set-orientation": "orientation set",
  "get-orientation": "orientation get",
  "set-fullscreen": "fullscreen set",
  "get-fullscreen": "fullscreen get",
  "set-renderer": "renderer set",
  "get-renderer": "renderer get",
  "get-viewport-presets": "viewport-preset list",
  "set-viewport-preset": "viewport-preset set",
  "show-commentary": "commentary show",
  "hide-commentary": "commentary hide",
  highlight: "highlight show",
  "hide-highlight": "highlight hide",
  "play-script": "script run",
  "abort-script": "script abort",
  "get-script-status": "script status",
  "ai-load": "ai load",
  "ai-ask": "ai ask",
  "ai-cancel": "ai cancel",
  "ai-endpoints": "ai endpoint list",
  "ai-endpoint-save": "ai endpoint add",
  "ai-endpoint-remove": "ai endpoint remove",
  "ai-endpoint-models": "ai endpoint models",
  "ai-endpoint-test": "ai endpoint test",
  "ai-endpoint-health": "ai endpoint health",
};

export const cliToEndpointCommandAliases: Record<string, string> = {
  ...Object.fromEntries(
    Object.entries(endpointToCliCommandAliases).map(([endpoint, cli]) => [cli, endpoint]),
  ),
  "dialog dismiss": "handle-dialog",
  "ai endpoint edit": "ai-endpoint-save",
  "ai endpoint use": "ai-load",
};
