#include "native_window_control.h"
namespace kelpie::windows { namespace { constexpr UINT kRun=WM_APP+0x531; }
bool NativeWindowControl::Create(HINSTANCE instance,HWND browser,int width,int height){owner_thread_id_=GetCurrentThreadId();browser_=browser;default_width_=width;default_height_=height;WNDCLASSW wc{};wc.lpfnWndProc=Proc;wc.hInstance=instance;wc.lpszClassName=L"KelpieNativeControl";RegisterClassW(&wc);dispatcher_=CreateWindowExW(0,wc.lpszClassName,L"",0,0,0,0,0,HWND_MESSAGE,nullptr,instance,this);return dispatcher_!=nullptr;}
void NativeWindowControl::Shutdown(){queue_.Cancel();if(dispatcher_){DestroyWindow(dispatcher_);dispatcher_=nullptr;}}
bool NativeWindowControl::Invoke(std::function<void()> task,std::chrono::milliseconds timeout){if(!dispatcher_)return false;if(is_owner_thread()){try{task();return true;}catch(...){return false;}}auto pending=queue_.Enqueue(std::move(task));if(!PostMessageW(dispatcher_,kRun,0,0)){queue_.Cancel();return false;}return queue_.Wait(pending,timeout);}
LRESULT CALLBACK NativeWindowControl::Proc(HWND hwnd,UINT message,WPARAM,LPARAM lparam){auto* self=reinterpret_cast<NativeWindowControl*>(GetWindowLongPtrW(hwnd,GWLP_USERDATA));if(message==WM_NCCREATE){self=static_cast<NativeWindowControl*>(reinterpret_cast<CREATESTRUCTW*>(lparam)->lpCreateParams);SetWindowLongPtrW(hwnd,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}if(message==kRun&&self){self->queue_.RunOne();return 0;}return DefWindowProcW(hwnd,message,0,lparam);}
void NativeWindowControl::SetFullscreen(bool enabled){if(!browser_||enabled==fullscreen_)return;HWND top=GetAncestor(browser_,GA_ROOT);if(enabled){saved_style_=GetWindowLongPtrW(top,GWL_STYLE);GetWindowPlacement(top,&saved_placement_);MONITORINFO m{sizeof(m)};GetMonitorInfoW(MonitorFromWindow(top,MONITOR_DEFAULTTONEAREST),&m);SetWindowLongPtrW(top,GWL_STYLE,saved_style_&~WS_OVERLAPPEDWINDOW);SetWindowPos(top,HWND_TOP,m.rcMonitor.left,m.rcMonitor.top,m.rcMonitor.right-m.rcMonitor.left,m.rcMonitor.bottom-m.rcMonitor.top,SWP_FRAMECHANGED|SWP_SHOWWINDOW);}else{SetWindowLongPtrW(top,GWL_STYLE,saved_style_);SetWindowPlacement(top,&saved_placement_);SetWindowPos(top,nullptr,0,0,0,0,SWP_FRAMECHANGED|SWP_NOMOVE|SWP_NOSIZE|SWP_NOZORDER);}fullscreen_=enabled;}
void NativeWindowControl::Resize(int width,int height){if(!browser_)return;HWND top=GetAncestor(browser_,GA_ROOT);RECT client{};GetClientRect(browser_,&client);RECT outer{};GetWindowRect(top,&outer);SetWindowPos(top,nullptr,outer.left,outer.top,outer.right-outer.left+(width-(client.right-client.left)),outer.bottom-outer.top+(height-(client.bottom-client.top)),SWP_NOZORDER);}
void NativeWindowControl::ResetViewport(){Resize(default_width_,default_height_);}
RECT NativeWindowControl::viewport()const{RECT r{};if(browser_)GetClientRect(browser_,&r);return r;}
}
