# Embeds files verbatim into a generated C++ translation unit.
#
# The start page ships as real `.html` / `.css` / `.js` / `.png` files so they
# stay editable and lintable, but the engine must serve them without depending on
# an install layout. This turns each file into a byte array at configure time.
# The generated source lives in the build tree and is never committed.
#
#   kelpie_embed_resources(
#     OUTPUT  <generated .cpp path>
#     HEADER  <relative include emitted into the .cpp>
#     NAMESPACE <fully qualified namespace>
#     RESOURCES <symbol>=<file> [<symbol>=<file> ...])
#
# Each entry declares `extern const std::string_view <symbol>;` — the caller's
# header is responsible for those declarations.
function(kelpie_embed_resources)
  cmake_parse_arguments(EMBED "" "OUTPUT;HEADER;NAMESPACE" "RESOURCES" ${ARGN})
  if(NOT EMBED_OUTPUT OR NOT EMBED_NAMESPACE)
    message(FATAL_ERROR "kelpie_embed_resources requires OUTPUT and NAMESPACE")
  endif()

  set(generated "// Generated by cmake/EmbedResource.cmake. Do not edit; do not commit.\n")
  if(EMBED_HEADER)
    string(APPEND generated "#include \"${EMBED_HEADER}\"\n\n")
  endif()
  string(APPEND generated "namespace ${EMBED_NAMESPACE} {\n\n")

  foreach(entry IN LISTS EMBED_RESOURCES)
    string(REGEX MATCH "^([^=]+)=(.*)$" matched "${entry}")
    if(NOT matched)
      message(FATAL_ERROR "kelpie_embed_resources: expected <symbol>=<file>, got '${entry}'")
    endif()
    set(symbol "${CMAKE_MATCH_1}")
    set(path "${CMAKE_MATCH_2}")
    if(NOT EXISTS "${path}")
      message(FATAL_ERROR "kelpie_embed_resources: missing resource ${path}")
    endif()
    # Re-run configure whenever the source asset changes, otherwise an edited
    # HTML file would keep serving the previously generated bytes.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${path}")

    file(READ "${path}" hex HEX)
    string(LENGTH "${hex}" hex_length)
    math(EXPR byte_count "${hex_length} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
    # Wrap at 16 bytes per line so the generated file stays within what every
    # supported compiler and editor handles comfortably.
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n    " bytes "${bytes}")

    string(APPEND generated "namespace {\nconstexpr char k${symbol}Bytes[] = {\n    ${bytes}\n};\n}  // namespace\n\n")
    string(APPEND generated
      "const std::string_view ${symbol}(k${symbol}Bytes, ${byte_count});\n\n")
  endforeach()

  string(APPEND generated "}  // namespace ${EMBED_NAMESPACE}\n")

  # `configure_file`-style write: only touch the file when the content changed so
  # incremental builds do not recompile the embedded assets every configure.
  set(existing "")
  if(EXISTS "${EMBED_OUTPUT}")
    file(READ "${EMBED_OUTPUT}" existing)
  endif()
  if(NOT existing STREQUAL generated)
    file(WRITE "${EMBED_OUTPUT}" "${generated}")
  endif()
endfunction()
