// --- Pairing & Auth ---

/**
 * `POST /v1/pair` request body. Both fields are caller-supplied and treated as
 * untrusted display data by the server: `clientName` is sanitized and labeled
 * "self-reported" in the device approval prompt.
 */
export interface PairRequest {
  /** Stable per-install UUID generated by the CLI. */
  clientId: string;
  /** Human-readable client name, such as `username@hostname`. Truncated to 64 chars. */
  clientName: string;
}

/** Initial response from `POST /v1/pair`. */
export interface PairResponse {
  status: "pending";
  /** Server-issued 32-byte CSPRNG nonce used to poll status. */
  requestId: string;
  /** Unix epoch ms when the pending request expires. */
  expiresAt: number;
  /** Authoritative socket peer address as seen by the server. */
  sourceAddress: string;
}

/**
 * Scope of an approved pairing.
 *
 * - `session`: kept in device memory only; cleared on app restart.
 * - `persistent`: written to the device's pairings store; survives restart.
 */
export type PairScope = "session" | "persistent";

export type PairStatusState =
  | "pending"
  | "approved"
  | "denied"
  | "expired"
  | "not_found";

/**
 * `GET /v1/pair/status?requestId=...` response. The plaintext `token` is
 * returned exactly once on approval; the pending entry is deleted server-side
 * immediately afterwards.
 */
export interface PairStatusResponse {
  status: PairStatusState;
  scope?: PairScope;
  token?: string;
}

/** `GET /v1/get-device-info` advertises that pairing is required. */
export interface DeviceInfoPairing {
  name: string;
  platform: string;
  version: string;
  requiresPairing: true;
}
